[package]
name = "doryani"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.10", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.216", features = ["derive"] }
shellexpand = "3.1.0"
toml = "0.8.19"
url = "2.5.4"
